import {DataRepository} from './lib/data.mjs';
import {atOrBefore} from './lib/logic.mjs';
import {marketForPage,overviewFile,marketPageURL} from './lib/routes.mjs';
import * as V from './lib/views.mjs';
const $=s=>document.querySelector(s);
const params=new URLSearchParams(location.search);
const page=location.pathname.endsWith('theme.html')?'theme':location.pathname.endsWith('history.html')?'history':location.pathname.endsWith('about.html')?'about':'overview';
const state={mode:params.get('data')==='mock'?'mock':'live',market:marketForPage(location.pathname,params.get('market')||''),period:params.get('period')==='weekly'?'weekly':'daily',key:params.get('date'),id:params.get('id'),search:'',filter:'all',sort:'rank',selected:[],researchTheme:params.get('theme')||'all',setupFilter:['candidate','ready','all','extended'].includes(params.get('setups'))?params.get('setups'):'candidate'};
const repo=new DataRepository();
let ctx,hist,drivers,candidates,renderVersion=0,invalidDate=false;
const activeKey=()=>`theme-atlas.v2.active.${state.market}`;
function activeIds(){try{const saved=localStorage.getItem(activeKey());if(saved)return (Array.isArray(JSON.parse(saved))?JSON.parse(saved):[]).filter(id=>ctx.rows.some(t=>t.id===id));}catch{}return [];}
function saveActive(ids){try{localStorage.setItem(activeKey(),JSON.stringify(ids));return true;}catch{document.querySelector('.storage-note')?.remove();const n=document.createElement('p');n.className='storage-note warning';n.textContent='端末内保存ができませんでした。再読込すると選択が解除されます。';$('.main').prepend(n);return false;}}
function url(file,extra={}){return `${file}?${new URLSearchParams({data:state.mode,market:state.market.toLowerCase(),period:state.period,date:state.key,...extra})}`;}
function syncURL(){const extra=page==='theme'?{id:state.id||''}:page==='overview'?{theme:state.researchTheme,setups:state.setupFilter}:{};history.replaceState(null,'',url(location.pathname,extra));}
const sections=[['market-health','Market Health'],['institutional','Institutional Focus'],['translation','Theme Translation'],['opportunities','New Entry'],['active-health','Theme Health'],['landscape','Landscape'],['theme-leaders','Theme Leaders'],['setups','Setups'],['rotation','Rotation']];
function shell(content){return `<aside class="rail"><a class="brand" href="${marketPageURL(state)}"><span class="brand-icon">▥</span><span>THEME<br>ATLAS</span></a><span class="eyebrow rail-label">RESEARCH DESK</span><nav aria-label="メインナビゲーション">${[['overview',overviewFile(state.market),'Overview'],['history','history.html','History'],['about','about.html','評価ロジック']].map(([p,f,n])=>`<a class="nav-link ${page===p||(p==='overview'&&page==='theme')?'active':''}" href="${url(f)}">${n}</a>`).join('')}</nav><nav class="section-nav" aria-label="判断フロー">${sections.map(([id,n],i)=>`<a href="${page==='overview'?'':marketPageURL(state)}#${id}"><small>0${i+1}</small>${n}</a>`).join('')}</nav><div class="rail-bottom"><span class="status-dot"></span> PC PROTOTYPE<br>${ctx.mode==='mock'?'DEMO':'OBSERVED TECHNICALS'}<br><small>US / Japan independently</small></div></aside><div class="workspace"><header class="topbar"><span class="breadcrumb">RESEARCH <span>/</span> <b>${{overview:'Overview',theme:'Theme Detail',history:'History',about:'Methodology'}[page]}</b></span><div class="top-controls"><div class="segmented" aria-label="データ切替">${[["live","Observed"],["mock","Demo"]].map(([v,n])=>`<button data-mode="${v}" aria-pressed="${state.mode===v}">${n}</button>`).join('')}</div>${V.badge(ctx.mode.toUpperCase(),ctx.mode==='mock'?'warning':'neutral')}<div class="segmented" aria-label="市場切替">${[['US','米国株'],['JP','日本株']].map(([v,n])=>`<a href="${marketPageURL(state,v)}" ${state.market===v?'aria-current="page"':''}>${n}</a>`).join('')}</div><div class="segmented" aria-label="評価期間">${['daily','weekly'].map(p=>`<button data-period="${p}" aria-pressed="${state.period===p}">${p==='daily'?'Daily':'Weekly'}</button>`).join('')}</div><label class="date-picker"><span class="sr-only">評価日・評価週</span><select id="date-select">${[...repo.manifest[state.period]].reverse().map(e=>`<option value="${e.key}" ${state.key===e.key?'selected':''}>${state.period==='daily'?e.asOf:e.key+' · '+e.asOf}</option>`).join('')}</select></label></div></header><main class="main">${invalidDate?'<div class="load-warning">指定された評価日がありません。直近の評価日へ切替しました。</div>':''}${content}<footer><span>THEME ATLAS · SWING RESEARCH</span><span>${ctx.entry.asOf} · ${state.market} · ${ctx.mode.toUpperCase()} · ${V.esc(ctx.config.version)}</span></footer></main></div>`;}
function candidatePanel(){if(ctx.mode!=='mock')return `<section class="panel" id="candidates"><div class="section-head"><div><h2>新規テーマ候補</h2><p>ニュースに基づく新テーマ発見は未接続です。Energy・Gold・Utilities等の構成銘柄は実データで評価しています。</p></div></div></section>`;return `<section class="panel" id="candidates"><div class="section-head"><div><h2>新規テーマ候補</h2><p>分類を拡張するための候補例。実際の採用判断・TradingViewへの反映は未実施。</p></div>${V.badge('MOCK','warning')}</div><div class="candidate-grid">${(candidates?.markets[state.market]??[]).map((c,i)=>`<button class="candidate-card" data-candidate="${i}"><strong>${V.esc(c.name)} ↗</strong><span>${V.esc(c.symbols.join(' / '))}</span><small>${V.esc(c.reason)}</small></button>`).join('')}</div></section>`;}
function content(){const ids=activeIds();if(page==='theme')return V.detail(ctx,state,state.id,hist);if(page==='history')return V.historyView(ctx,state,hist,drivers);if(page==='about')return V.about(ctx);return V.hero(ctx,state,ids)+V.marketHealth(ctx)+V.institutional(ctx)+V.translations(ctx,state)+V.opportunities(ctx,state)+V.activeThemes(ctx,state,ids)+V.landscape(ctx,state)+V.themeLeaders(ctx,state)+V.setups(ctx,state)+V.rotation(ctx,state,hist,state.selected)+candidatePanel();}
function draw(){document.title=`${state.market==='US'?'米国株':'日本株'} — Theme Atlas`;syncURL();$('#app').innerHTML=shell(content());if(page==='overview'){tableBody();researchBody();}bind();}
function tableBody(){const result=V.landscapeRows(ctx,state,activeIds());$('#ranking-body').innerHTML=result.html;$('#result-count').textContent=`${result.count} / ${ctx.rows.length} themes · ${state.period.toUpperCase()} ${ctx.entry.asOf}`;bindPins();}
function researchBody(){const leaders=V.leaderRows(ctx,state),setups=V.setupRows(ctx,state);$('#leader-body').innerHTML=leaders.html;$('#leader-count').textContent=`${leaders.count} leaders · 各テーマTop 3`;$('#setup-body').innerHTML=setups.html;$('#setup-count').textContent=`${setups.count} / ${setups.total} setups · Entry候補 ${setups.candidates}`;document.querySelectorAll('[data-research-link]').forEach(a=>a.onclick=()=>{state.researchTheme=a.dataset.researchLink;state.setupFilter='all';document.querySelectorAll('[data-research-theme]').forEach(el=>el.value=state.researchTheme);$('#setup-filter').value=state.setupFilter;syncURL();researchBody();});}
function bindPins(){document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{const id=b.dataset.pin,ids=activeIds();if(saveActive(ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]))draw();});document.querySelectorAll('[data-remove-active]').forEach(b=>b.onclick=()=>{if(saveActive(activeIds().filter(x=>x!==b.dataset.removeActive)))draw();});}
function bind(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{const p=new URLSearchParams(location.search);p.set('data',b.dataset.mode);p.delete('date');location.href=location.pathname+'?'+p;});document.querySelectorAll('[data-period]').forEach(b=>b.onclick=async()=>{if(state.period===b.dataset.period)return;const asOf=ctx.selected.asOf;state.period=b.dataset.period;state.key=atOrBefore(repo.manifest[state.period],asOf)?.key??repo.manifest[state.period][0].key;state.selected=[];await render();});$('#date-select').onchange=async e=>{state.key=e.target.value;await render();};bindPins();if(page==='overview'){document.querySelectorAll('[data-research-theme]').forEach(el=>el.onchange=e=>{state.researchTheme=e.target.value;document.querySelectorAll('[data-research-theme]').forEach(other=>other.value=state.researchTheme);syncURL();researchBody();});$('#setup-filter').onchange=e=>{state.setupFilter=e.target.value;syncURL();researchBody();};$('#theme-search').oninput=e=>{state.search=e.target.value;tableBody();};$('#sort-select').onchange=e=>{state.sort=e.target.value;tableBody();};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(el=>el.classList.toggle('selected',el===b));tableBody();});document.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=()=>{const c=candidates.markets[state.market][+b.dataset.candidate],dialog=$('#candidate-dialog');dialog.innerHTML=`<button class="dialog-close">閉じる ×</button>${V.badge('MOCK CANDIDATE','warning')}<h2>${V.esc(c.name)}</h2><p>${V.esc(c.reason)}</p><p>${V.esc(c.symbols.join(' / '))}</p><p class="muted">分類の独立性・流動性・継続的な強さを確認する候補例です。</p>`;dialog.querySelector('button').onclick=()=>dialog.close();dialog.showModal();});}document.querySelectorAll('[data-history]').forEach(b=>b.onchange=()=>{state.selected=[...document.querySelectorAll('[data-history]:checked')].map(x=>x.dataset.history);$('#rank-line').innerHTML=V.rankChart(ctx,state,hist,state.selected);document.querySelectorAll('[data-history]').forEach(el=>el.disabled=state.selected.length>=4&&!el.checked);});}
async function render(){const version=++renderVersion;document.querySelectorAll('[data-market],[data-period],#date-select').forEach(el=>el.disabled=true);try{const next=await repo.context(state.period,state.key,state.market);if(version!==renderVersion)return;ctx=next;if(state.researchTheme!=='all'&&!ctx.rows.some(t=>t.id===state.researchTheme))state.researchTheme='all';state.selected=state.selected.filter(id=>ctx.rows.some(t=>t.id===id));if(page==='theme'&&!state.id)state.id=ctx.rows[0].id;[hist,drivers]=await Promise.all([repo.history(state.period,ctx.entry.asOf,state.market),page==='history'?repo.driverHistory(ctx.entry.asOf,state.market):[]]);if(version!==renderVersion)return;draw();}catch(e){if(version!==renderVersion)return;$('#app').innerHTML=`<div class="error"><h1>データを読み込めませんでした</h1><p>最終成功評価を取得できないため、評価を表示していません。</p><p>${V.esc(e.message)}</p><button id="retry" class="outline-btn">再読み込み</button></div>`;$('#retry').onclick=()=>location.reload();console.error(e);}}
async function start(){if(page==='overview'&&!/\/(us|japan)\.html$/.test(location.pathname)){const p=new URLSearchParams(location.search);p.set('market',state.market.toLowerCase());location.replace(overviewFile(state.market)+'?'+p+location.hash);return;}try{await repo.load(state.mode);candidates=await repo.json('data/candidates.json').catch(()=>null);invalidDate=!!state.key&&!repo.manifest[state.period].some(e=>e.key===state.key);if(!state.key||invalidDate)state.key=repo.manifest[state.period].at(-1).key;await render();}catch(e){$('#app').innerHTML=`<div class="error"><h1>データ構成を取得できませんでした</h1><p>${V.esc(e.message)}</p><button id="retry">再読み込み</button></div>`;$('#retry').onclick=()=>location.reload();console.error(e);}}
start();
