import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {DataRepository} from '../lib/data.mjs';
import {weighted,opportunity,activeHealth,confirmation,atOrBefore,dataStatus,marketTrend} from '../lib/logic.mjs';
import * as V from '../lib/views.mjs';
const root=new URL('../',import.meta.url);
const fixture=async path=>JSON.parse(await readFile(new URL(path,root),'utf8'));
const config=await fixture('config/scoring.json');
const fetcher=async path=>{try{return {ok:true,json:()=>fixture(path)}}catch{return {ok:false,status:404}}};
const make=async()=>new DataRepository(fetcher).load();
const base={quantitative:{dailyAcceleration:94,above50:82,above200:74,setupReady:3,extensionPct:3,dailyRank:2,weeklyRank:8,weeklyRankChange:2,breadthDelta5:8,leaderRSDelta5:3,weeklyDelta5:4,weeklyDelta3Weeks:4,breakouts:10,failedBreakouts:1},scores:{weekly:78,leaderQuality:90}};
test('weighted scores require all inputs; configured weights normalize',()=>{assert.equal(weighted({a:80,b:60},{a:.7,b:.3}),74);assert.equal(weighted({a:80},{a:.7,b:.3}),null);assert.equal(weighted({a:null},{a:1}),null);});
test('extension and missing setup override an attractive score; market gates entry',()=>{assert.equal(opportunity(base,75,config).status,'EMERGING');const extended=structuredClone(base);extended.quantitative.extensionPct=15;assert.equal(opportunity(extended,75,config).eligible,false);assert.equal(opportunity(extended,75,config).status,'EXTENDED');const noSetup=structuredClone(base);noSetup.quantitative.setupReady=0;assert.equal(opportunity(noSetup,75,config).eligible,false);assert.equal(opportunity(base,40,config).eligible,false);});
test('short weakness alone is WATCH; deterioration needs a medium-term break',()=>{const t=structuredClone(base);t.quantitative.weeklyDelta5=-12;assert.equal(activeHealth(t,config).status,'WATCH');t.quantitative.weeklyDelta3Weeks=-18;t.quantitative.above200=35;assert.equal(activeHealth(t,config).status,'DETERIORATING');});
test('macro positive is unconfirmed without rank, breadth, and leader evidence',()=>{assert.equal(confirmation(base),'CONFIRMED TAILWIND');const t=structuredClone(base);t.quantitative.dailyRank=null;assert.equal(confirmation(t),'UNCONFIRMED');t.quantitative.dailyRank=2;t.quantitative.leaderRSDelta5=-2;assert.equal(confirmation(t),'UNCONFIRMED');});
test('states distinguish mock, archive, failed updates, and malformed live timestamp',()=>{const a={mode:'mock',asOf:'2026-10-01',latestAsOf:'2026-10-01'};assert.equal(dataStatus(a).label,'MOCK DATA');assert.equal(dataStatus({...a,asOf:'2026-09-28'}).label,'ARCHIVE');assert.equal(dataStatus({...a,failures:['missing']} ).label,'STALE DATA');assert.equal(dataStatus({...a,mode:'live',lastSuccessfulUpdate:'bad'}).label,'INVALID DATA');assert.equal(dataStatus({...a,mode:'live',lastSuccessfulUpdate:'2026-09-30T06:00Z',expectedNextUpdate:'2026-10-01T06:00Z'},new Date('2026-10-01T07:00Z')).label,'STALE DATA');});
test('weekly data and AI history never come from the future; real archived deltas',async()=>{const repo=await make();for(const period of ['daily','weekly']){for(const entry of repo.manifest[period]){const ctx=await repo.context(period,entry.key,'US');assert.ok(!ctx.pair.weekly||ctx.pair.weekly.asOf<=entry.asOf);assert.ok(!ctx.pair.daily||ctx.pair.daily.asOf<=entry.asOf);assert.equal(ctx.analysisMeta.date,entry.asOf);for(const t of ctx.rows){assert.equal(t.scores.weekly,ctx.pair.weekly?.markets.US.themes.find(w=>w.id===t.id).scores.weekly??null);}}}const ctx=await repo.context('daily','2026-09-21','US');const drivers=await repo.driverHistory(ctx.entry.asOf,'US');assert.ok(drivers.every(d=>d.entry.asOf<='2026-09-21'));assert.equal(atOrBefore(repo.manifest.weekly,'2026-09-21').key,'2026-W38');});
test('snapshot fetch failure falls back visibly as STALE, never silently latest',async()=>{const failed='data/mock/daily/2026-10-01.json';const repo=await new DataRepository(async path=>path===failed?{ok:false,status:503}:fetcher(path)).load();const ctx=await repo.context('daily','2026-10-01','US');assert.equal(ctx.entry.asOf,'2026-09-30');assert.equal(ctx.status.label,'STALE DATA');assert.ok(ctx.failures[0].includes('503'));});
test('Mock/Live mixing is rejected',async()=>{const repo=await make();repo.router.mode='live';await assert.rejects(()=>repo.snapshot('daily','2026-10-01'),/モード/);});
test('all snapshots preserve original membership and scores match the config',async()=>{const repo=await make(),catalog=await fixture('data/theme-catalog.json');for(const period of ['daily','weekly']){for(const e of repo.manifest[period]){const doc=await repo.snapshot(period,e.key);for(const market of ['US','JP']){const m=doc.markets[market];assert.equal(m.scores.marketHealth,weighted(m.scores.marketComponents,config.marketHealth));assert.deepEqual(m.themes.map(t=>t.quantitative[period+'Rank']).sort((a,b)=>a-b),Array.from({length:m.themes.length},(_,i)=>i+1));for(const t of m.themes){const original=catalog.markets[market].themes.find(c=>c.id===t.id);if(original)assert.deepEqual(t.symbols,original.symbols);else assert.equal(t.catalogOrigin,'mock-extension');assert.equal(t.scores.daily,weighted(t.scores.dailyComponents,config.daily));assert.equal(t.scores.weekly,weighted(t.scores.weeklyComponents,config.weekly));for(const s of t.stocks){assert.equal(s.scores.leader,weighted(s.scores.components,config.leader));assert.ok(s.quantitative.stop<s.quantitative.entry);}assert.equal(t.quantitative.setupReady,t.stocks.filter(s=>s.quantitative.setupReady).length);assert.equal(t.scores.leaderQuality,t.stocks[0].scores.leader);}}}}});
test('all page views render and escape external strings; rank chart breaks on missing snapshots',async()=>{const repo=await make(),ctx=await repo.context('daily','2026-10-01','US'),state={market:'US',period:'daily',key:'2026-10-01',selected:[],search:'',sort:'rank',filter:'all'},hist=await repo.history('daily',ctx.entry.asOf,'US');assert.ok(V.hero(ctx,state,[]).includes('MOCK DATA'));for(const fn of ['marketHealth','institutional','translations','opportunities','activeThemes','landscape','rotation','about'])assert.ok(V[fn](ctx,state,fn==='activeThemes'?[]:hist,[]).length>100);assert.ok(V.detail(ctx,state,'us-6',hist).includes('THEME LEADERS'));assert.ok(V.historyView(ctx,state,hist,await repo.driverHistory(ctx.entry.asOf,'US')).includes('MARKET DRIVER HISTORY'));assert.equal(V.esc('<script>'),'&lt;script&gt;');const id=ctx.rows[0].id;assert.equal((V.rankChart(ctx,state,[hist[0],{...hist[1],rows:null},hist[2]],[id]).match(/<polyline/g)||[]).length,2);assert.ok(marketTrend({change1M:16,changeUnit:'bp',price:4.1,ma50:4,slope50:.1}).label.includes('Strong Up'));});

test("default fetch preserves native receiver",async()=>{const old=globalThis.fetch;try{globalThis.fetch=function(path){assert.ok(!(this instanceof DataRepository));return fetcher(path);};assert.equal((await new DataRepository().load()).router.mode,"mock");}finally{globalThis.fetch=old;}});

test("historical views use the saved scoring version after configuration changes",async()=>{const repo=await make();repo.config={...repo.config,version:"future",opportunity:{weeklyStrength:1}};const ctx=await repo.context("daily","2026-09-21","US");assert.equal(ctx.config.version,"2.0.0-prototype");assert.equal(ctx.config.opportunity.dailyAcceleration,.2);});
