import {atOrBefore,dataStatus} from './logic.mjs';
export class DataRepository {
 constructor(fetcher=(...args)=>fetch(...args)){this.fetcher=fetcher;this.cache=new Map();this.failures=[];}
 async json(path){if(this.cache.has(path))return this.cache.get(path);const r=await this.fetcher(path,{cache:'no-cache'});if(!r.ok)throw Error(`${path}: HTTP ${r.status}`);const doc=await r.json();this.cache.set(path,doc);return doc;}
 async load(){this.router=await this.json('data/latest.json');if(this.router.schemaVersion!==2)throw Error('データ版と画面版が一致しません');this.manifest=await this.json('data/'+this.router.manifestPath);this.config=await this.json('config/scoring.json');if(this.manifest.mode!==this.router.mode)throw Error('Mock / Liveデータの混在を検出');return this;}
 async snapshot(period,key){const entry=this.manifest[period].find(e=>e.key===key);if(!entry)throw Error('該当する評価日がありません');const doc=await this.json('data/'+entry.path);if(doc.mode!==this.router.mode||doc.asOf!==entry.asOf||doc.period!==period)throw Error('データモード不一致');return doc;}
 async context(period,key,market){this.failures=[];const selected=this.manifest[period].find(e=>e.key===key)||this.manifest[period].at(-1);let current;let entry=selected;
  try{current=await this.snapshot(period,entry.key);}catch(e){this.failures.push(e.message);const older=this.manifest[period].filter(d=>d.asOf<entry.asOf).reverse();for(const candidate of older){try{current=await this.snapshot(period,candidate.key);entry=candidate;break;}catch{/* Try the next archived file; always report STALE. */}}if(!current)throw e;}
  const pair={};for(const p of ['daily','weekly']){const e=atOrBefore(this.manifest[p],entry.asOf);if(e){try{pair[p]=await this.snapshot(p,e.key);}catch(err){this.failures.push(`${p}評価が取得できません: ${err.message}`);pair[p]=null;}}else pair[p]=null;}
  let analysis=null,raw=null;try{analysis=await this.json('data/'+entry.analysisPath);if(analysis.mode!==this.router.mode||analysis.date!==entry.asOf)throw Error('AIデータモード不一致');}catch(e){analysis=null;this.failures.push('AI解釈未取得: '+e.message);}
  try{raw=await this.json('data/'+entry.rawPath);if(raw.mode!==this.router.mode||raw.asOf!==entry.asOf)throw Error('Rawデータモード不一致');}catch(e){raw=null;this.failures.push('Raw data未取得: '+e.message);}
  const previous={};for(const p of ['daily','weekly']){const asOf=pair[p]?.asOf;const prev=asOf?atOrBefore(this.manifest[p],this.manifest[p].filter(e=>e.asOf<asOf).at(-1)?.asOf??''):null;previous[p]=prev?await this.snapshot(p,prev.key).catch(()=>null):null;}
  const rows=current.markets[market].themes.map(t=>{const d=pair.daily?.markets[market].themes.find(x=>x.id===t.id),w=pair.weekly?.markets[market].themes.find(x=>x.id===t.id);const pd=previous.daily?.markets[market].themes.find(x=>x.id===t.id),pw=previous.weekly?.markets[market].themes.find(x=>x.id===t.id);return {...t,quantitative:{...t.quantitative,dailyRank:d?.quantitative.dailyRank??null,weeklyRank:w?.quantitative.weeklyRank??null,dailyRankChange:pd&&d?pd.quantitative.dailyRank-d.quantitative.dailyRank:null,weeklyRankChange:pw&&w?pw.quantitative.weeklyRank-w.quantitative.weeklyRank:null},scores:{...t.scores,daily:d?.scores.daily??null,weekly:w?.scores.weekly??null,dailyComponents:d?.scores.dailyComponents??{},weeklyComponents:w?.scores.weeklyComponents??{}},ai:analysis?.markets[market]?.themes[t.id]??null};});
  const config=current.evaluationVersion===this.config.version?this.config:await this.json('config/versions/'+encodeURIComponent(current.evaluationVersion)+'.json');if(config.version!==current.evaluationVersion)throw Error('評価時点の設定版を取得できません');const health=current.markets[market].scores.marketHealth;const latest=this.manifest[period].at(-1).asOf;return {entry,selected,current,pair,rows,analysis:analysis?.markets[market]??null,analysisMeta:analysis,raw:raw?.markets[market]??null,market:current.markets[market],config,health,mode:this.router.mode,failures:[...this.failures],status:dataStatus({mode:this.router.mode,asOf:entry.asOf,latestAsOf:latest,lastSuccessfulUpdate:this.manifest.lastSuccessfulUpdate,expectedNextUpdate:this.manifest.expectedNextUpdate,failures:this.failures}),lastUpdated:this.manifest.lastSuccessfulUpdate};
 }
 async history(period,asOf,market){const entries=this.manifest[period].filter(e=>e.asOf<=asOf);const results=await Promise.allSettled(entries.map(e=>this.snapshot(period,e.key)));return results.map((r,i)=>({entry:entries[i],rows:r.status==='fulfilled'?r.value.markets[market].themes:null,error:r.status==='rejected'?r.reason.message:null}));}
 async driverHistory(asOf,market){const entries=this.manifest.daily.filter(e=>e.asOf<=asOf);const docs=await Promise.allSettled(entries.map(e=>this.json('data/'+e.analysisPath).then(doc=>{if(doc.mode!==this.router.mode||doc.date!==e.asOf)throw Error('AI履歴のモード/日付不一致');return doc;})));return docs.map((r,i)=>({entry:entries[i],analysis:r.status==='fulfilled'?r.value.markets[market]:null,meta:r.status==='fulfilled'?r.value:null}));}
}
